### ISSUE TITLE
单击会出现BUG

### ISSUE THREAD

**Issue by Godfather6666** [LuodiJackShen/GesturePasswordWidget#1]
return GesturePasswordWidget(
      lineColor: Colors.white,
      errorLineColor: Colors.redAccent,
      singleLineCount: 3,
      identifySize: 80.0,
      minLength: 4,
      hitShowMilliseconds: 40,
      errorItem: Container(
        width: 10.0,
        height: 10.0,
        decoration: BoxDecoration(
          color: Colors.redAccent,
          borderRadius: BorderRadius.circular(50.0),
        ),
      ),
      normalItem: Container(
        width: 10.0,
        height: 10.0,
        decoration: BoxDecoration(
          color: Colors.white,
          borderRadius: BorderRadius.circular(50.0),
        ),
      ),
      selectedItem: Container(
        width: 10.0,
        height: 10.0,
        decoration: BoxDecoration(
          color: Colors.blue,
          borderRadius: BorderRadius.circular(50.0),
        ),
      ),
      hitItem: Container(
        width: 15.0,
        height: 15.0,
        decoration: BoxDecoration(
          color: Colors.white,
          borderRadius: BorderRadius.circular(50.0),
        ),
      ),
      answer: [0, 1, 2, 4, 7],
      color: Color(0xff252534),
      onComplete: (data) {
        print(data);
      },
    );
  }
现在就是用注释里的demo，可以试试多点击几个按钮，手指摁下后显示selectedItem，松手之后并没有还原为normalItem，并且点击多个会出现连线状态，而且手离开屏幕连线状态还是会保持，请复现bug时使用单击并且不要滑动

**Comment by LuodiJackShen** [comment]
当一个手指点击一个点并且不松开时，此时再用另一个手指点击另一个点，flutter认为手指并没有离开屏幕，所以两点之间会有连线，当所有手指都松开时GesturePasswordWidget会恢复到初始化状态。我录了个视频，代码用的是你上面贴出来的代码，视频见：
![demo](https://user-images.githubusercontent.com/25525335/93979583-1d8be400-fdb0-11ea-85a4-25b783430191.gif)

但你说的这种情况我这是真没复现，方便的话你也录个视频发我邮箱吧luodijack@gmail.com，我来瞅瞅哪里的原因。
录视频的时候记得把开发者配置里的“显示点按反馈开关”打开：
![device-2020-09-23-150915](https://user-images.githubusercontent.com/25525335/93979399-de5d9300-fdaf-11ea-8095-cd65717ff61a.png)

**Comment by LuodiJackShen** [comment]
如邮件沟通，已经兼容您的手机，请更新使用最新版本 1.0.3
