### ISSUE TITLE
手势校验完成后如果直接关闭页面会闪退

### ISSUE THREAD

**Issue by 528526221** [LuodiJackShen/GesturePasswordWidget#2]
536行刷新操作是在延迟了[widget.completeWaitMilliseconds]之后进行操作的，但是在这之前会执行[widget.onComplete?.call(result)]，如果业务上在onComplete中关闭页面就会报错，建议在刷新之前可以检查mounted情况，当然如果有其他可以解决该问题的手段也可以。

**Comment by LuodiJackShen** [comment]
已经修改，1.0.6，感谢！
