### ISSUE TITLE
answer设置成变量传进去为啥拒绑定了

### ISSUE THREAD

**Issue by cctvbtv123456** [LuodiJackShen/GesturePasswordWidget#3]

**Comment by LuodiJackShen** [comment]
有代码吗？

**Comment by LuodiJackShen** [comment]
我把answer作为一个变量传进去，一切正常，代码如下：
  ```dart
List<int>? answer;

  @override
  void initState() {
    answer = [0, 1, 2, 4, 7];
    super.initState();
  }

Widget createNormalGesturePasswordView() {
    return GesturePasswordWidget(
      lineColor: const Color(0xff0C6BFE),
      errorLineColor: const Color(0xffFB2E4E),
      singleLineCount: 3,
      identifySize: 80.0,
      minLength: 4,
      errorItem: Image.asset(
        'images/error.png',
        color: const Color(0xffFB2E4E),
      ),
      normalItem: Image.asset('images/normal.png'),
      selectedItem: Image.asset(
        'images/selected.png',
        color: const Color(0xff0C6BFE),
      ),
      arrowItem: Image.asset(
        'images/arrow.png',
        width: 20.0,
        height: 20.0,
        color: const Color(0xff0C6BFE),
        fit: BoxFit.fill,
      ),
      errorArrowItem: Image.asset(
        'images/arrow.png',
        width: 20.0,
        height: 20.0,
        fit: BoxFit.fill,
        color: const Color(0xffFB2E4E),
      ),
      answer: answer,
      color: backgroundColor,
      onComplete: (data) {
        setState(() {
          result = data.join(', ');
        });
      },
    );
  }
```

**Comment by zhubowtbagod** [comment]
> 我把answer作为一个变量传进去，一切正常，代码如下：
> 
> ```dart
> List<int>? answer;
> 
> @override
> void initState() {
>   answer = [0, 1, 2, 4, 7];
>   super.initState();
> }
> 
> Widget createNormalGesturePasswordView() {
>   return GesturePasswordWidget(
>     lineColor: const Color(0xff0C6BFE),
>     errorLineColor: const Color(0xffFB2E4E),
>     singleLineCount: 3,
>     identifySize: 80.0,
>     minLength: 4,
>     errorItem: Image.asset(
>       'images/error.png',
>       color: const Color(0xffFB2E4E),
>     ),
>     normalItem: Image.asset('images/normal.png'),
>     selectedItem: Image.asset(
>       'images/selected.png',
>       color: const Color(0xff0C6BFE),
>     ),
>     arrowItem: Image.asset(
>       'images/arrow.png',
>       width: 20.0,
>       height: 20.0,
>       color: const Color(0xff0C6BFE),
>       fit: BoxFit.fill,
>     ),
>     errorArrowItem: Image.asset(
>       'images/arrow.png',
>       width: 20.0,
>       height: 20.0,
>       fit: BoxFit.fill,
>       color: const Color(0xffFB2E4E),
>     ),
>     answer: answer,
>     color: backgroundColor,
>     onComplete: (data) {
>       setState(() {
>         result = data.join(', ');
>       });
>     },
>   );
> }
> ```

这样设置以后，手势滑动错误的情况没有展示错误红色的布局？

**Comment by LuodiJackShen** [comment]
是有的啊，看下截图：

![WechatIMG490](https://user-images.githubusercontent.com/25525335/128689723-b86ade7b-a350-481d-ba90-9da45b8062c3.jpeg)

**Comment by zhubowtbagod** [comment]
> 是有的啊，看下截图：
> 
> ![WechatIMG490](https://user-images.githubusercontent.com/25525335/128689723-b86ade7b-a350-481d-ba90-9da45b8062c3.jpeg)

公司电脑估计鸹貔了，在家里电脑就可以，谢了大佬

**Comment by zhubowtbagod** [comment]
大佬另外想请教一下，如果组件放在SingleChildScrollView 内，可能导致的滑动冲突怎么解决
