### ISSUE TITLE
无法保存首次输入的手势密码

### ISSUE THREAD

**Issue by waitlt** [LuodiJackShen/GesturePasswordWidget#4]
我想实现的是连续输入两次手势作为新密码 ,但不管怎么保存都无法保存第一次用户输入的密码 因为两次输入密码不一致就要让用户重新输入密码直到输入正确为止！

**Comment by yanhao98** [comment]
这问题和该插件无任何关系。

**Comment by waitlt** [comment]
手势密码输入后的回调 返回的是一个list集合。这么说吧 您试着去实现一下连续输入两次密码为设置新密码.两次密码输入不一致就提醒用户 否则就设置成功 就这个问题 我整整测试了一天 不管用什么来存储第一次的状态都没用 您要是能用这个插件实现这个功能&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LuodiJackShen/GesturePasswordWidget"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月30日(星期四) 中午11:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [LuodiJackShen/GesturePasswordWidget] 无法保存首次输入的手势密码 (Issue #4)





 
这问题和该插件无任何关系。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yanhao98** [comment]
> 手势密码输入后的回调 返回的是一个list集合。这么说吧 您试着去实现一下连续输入两次密码为设置新密码.两次密码输入不一致就提醒用户 否则就设置成功 就这个问题 我整整测试了一天 不管用什么来存储第一次的状态都没用 您要是能用这个插件实现这个功能&nbsp;
> […](#)

我已经实现了。

**Comment by yanhao98** [comment]
哥们，这是你自己的问题。

**Comment by waitlt** [comment]
就回调里的代码能给我看看吗 谢谢您




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LuodiJackShen/GesturePasswordWidget"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月30日(星期四) 中午12:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [LuodiJackShen/GesturePasswordWidget] 无法保存首次输入的手势密码 (Issue #4)





  
手势密码输入后的回调 返回的是一个list集合。这么说吧 您试着去实现一下连续输入两次密码为设置新密码.两次密码输入不一致就提醒用户 否则就设置成功 就这个问题 我整整测试了一天 不管用什么来存储第一次的状态都没用 您要是能用这个插件实现这个功能&nbsp;
 …
  
我已经实现了。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by waitlt** [comment]
对啊 我无法解决这个问题 所以来请教您




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LuodiJackShen/GesturePasswordWidget"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月30日(星期四) 中午12:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [LuodiJackShen/GesturePasswordWidget] 无法保存首次输入的手势密码 (Issue #4)





 
哥们，这是你自己的问题。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yanhao98** [comment]
> 对啊 我无法解决这个问题 所以来请教您
> […](#)

谈不上请教，供你参考一下。
实现效果：https://bbbsp.oss-cn-beijing.aliyuncs.com/SVID_20211230_121738_1.mp4

这个屏幕的 controller 

```
import 'package:collection/collection.dart';
import 'package:flutter/material.dart';
import 'package:flutter_easyloading/flutter_easyloading.dart';
import 'package:get/get.dart';
import 'package:uuid/uuid.dart';

import '../../../../common/global/controllers/authentication_controller.dart';
import '../../../../services/app_api_service/app_api_service.dart';
import '../../../common/helpers/common_helper.dart';

class SetGesturePasswordController extends GetxController {
  SetGesturePasswordController({
    required this.onBindSuccess,
  });

  final VoidCallback onBindSuccess;

  /// 第一次绘制
  RxList<int> pointList = RxList();

  /// 第二次绘制
  RxList<int> pointAgainList = RxList();

  void handleGestureComplete(List<int?> result) {
    if (result.every((point) => point != null)) {
      final resultPointList = result.map((e) => e!).toList();

      if (pointList.length < 4) {
        // 处理第一次绘制
        pointList.value = resultPointList;
      } else {
        // 处理第二次绘制
        pointAgainList.value = resultPointList;

        if (const ListEquality().equals(pointList, pointAgainList)) {
          Log.d('两次一致，请求接口。');
          _handleBindBiometric(pointAgainList);
        }
      }
    } else {
      EasyLoading.showError('处理出错...');
    }

    Log.d('result: [${result.join(',')}], pointList: [${pointList.join(',')}], pointAgainList: [${pointAgainList.join(',')}], equals: [${const ListEquality().equals(pointList, pointAgainList)}]');
  }

  Future<void> _handleBindBiometric(List<int> pointList) async {
    final uuid = const Uuid().v4();
    try {
      EasyLoading.show(status: '设置中...', maskType: EasyLoadingMaskType.black);
      await AppApiService().bindBiometric(AppApiBiometricType.GESTURE, uuid);
      await AuthenticationController.to.handleBindGesturePasswordSuccess(pointList, uuid);
      onBindSuccess.call();
      EasyLoading.dismiss(animation: true).then((_) => EasyLoading.showSuccess('手势密码设置成功'));
    } catch (e) {
      EasyLoading.dismiss(animation: true).then((_) => EasyLoading.showError('$e'));
    }
  }
}

extension StateExt on SetGesturePasswordController {
  Widget obx({
    required Widget onDefault,
    required Widget onMinLengthError,
    required Widget onAgain,
    required Widget onNotEquals,
    required Widget onSuccess,
  }) {
    return Obx(() {
      final pointList = this.pointList;
      final pointAgainList = this.pointAgainList;

      // String? shownText;

      if ((pointList.isNotEmpty && pointList.length < 4) || //
          (pointAgainList.isNotEmpty && pointAgainList.length < 4)) {
        // shownText = '请至少连接4个点';
        return onMinLengthError;
      }

      if (pointList.isNotEmpty && pointAgainList.isEmpty) {
        // shownText = '请再次绘制手势密码';
        return onAgain;
      }

      if (pointList.isNotEmpty && pointAgainList.isNotEmpty) {
        if (!const ListEquality().equals(pointList, pointAgainList)) {
          // shownText = '两次图案不一样，请重新绘制';
          return onNotEquals;
        } else {
          // shownText = '正在设置...';
          return onSuccess;
        }
      }

      // return Text(shownText ?? '请绘制解锁图案');
      return onDefault;
    });
  }
}

```

**Comment by waitlt** [comment]
好的 谢谢您




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LuodiJackShen/GesturePasswordWidget"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月30日(星期四) 中午12:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [LuodiJackShen/GesturePasswordWidget] 无法保存首次输入的手势密码 (Issue #4)





  
对啊 我无法解决这个问题 所以来请教您
 …
  
谈不上请教，供你参考一下。
 实现效果：https://bbbsp.oss-cn-beijing.aliyuncs.com/SVID_20211230_121738_1.mp4
 
这个屏幕的 controller
 import 'package:collection/collection.dart'; import 'package:flutter/material.dart'; import 'package:flutter_easyloading/flutter_easyloading.dart'; import 'package:get/get.dart'; import 'package:uuid/uuid.dart'; import '../../../../common/global/controllers/authentication_controller.dart'; import '../../../../services/app_api_service/app_api_service.dart'; import '../../../common/helpers/common_helper.dart'; class SetGesturePasswordController extends GetxController {   SetGesturePasswordController({     required this.onBindSuccess,   });   final VoidCallback onBindSuccess;   /// 第一次绘制   RxList<int&gt; pointList = RxList();   /// 第二次绘制   RxList<int&gt; pointAgainList = RxList();   void handleGestureComplete(List<int?&gt; result) {     if (result.every((point) =&gt; point != null)) {       final resultPointList = result.map((e) =&gt; e!).toList();       if (pointList.length < 4) {         // 处理第一次绘制         pointList.value = resultPointList;       } else {         // 处理第二次绘制         pointAgainList.value = resultPointList;         if (const ListEquality().equals(pointList, pointAgainList)) {           Log.d('两次一致，请求接口。');           _handleBindBiometric(pointAgainList);         }       }     } else {       EasyLoading.showError('处理出错...');     }     Log.d('result: [${result.join(',')}], pointList: [${pointList.join(',')}], pointAgainList: [${pointAgainList.join(',')}], equals: [${const ListEquality().equals(pointList, pointAgainList)}]');   }   Future<void&gt; _handleBindBiometric(List<int&gt; pointList) async {     final uuid = const Uuid().v4();     try {       EasyLoading.show(status: '设置中...', maskType: EasyLoadingMaskType.black);       await AppApiService().bindBiometric(AppApiBiometricType.GESTURE, uuid);       await AuthenticationController.to.handleBindGesturePasswordSuccess(pointList, uuid);       onBindSuccess.call();       EasyLoading.dismiss(animation: true).then((_) =&gt; EasyLoading.showSuccess('手势密码设置成功'));     } catch (e) {       EasyLoading.dismiss(animation: true).then((_) =&gt; EasyLoading.showError('$e'));     }   } } extension StateExt on SetGesturePasswordController {   Widget obx({     required Widget onDefault,     required Widget onMinLengthError,     required Widget onAgain,     required Widget onNotEquals,     required Widget onSuccess,   }) {     return Obx(() {       final pointList = this.pointList;       final pointAgainList = this.pointAgainList;       // String? shownText;       if ((pointList.isNotEmpty &amp;&amp; pointList.length < 4) || //           (pointAgainList.isNotEmpty &amp;&amp; pointAgainList.length < 4)) {         // shownText = '请至少连接4个点';         return onMinLengthError;       }       if (pointList.isNotEmpty &amp;&amp; pointAgainList.isEmpty) {         // shownText = '请再次绘制手势密码';         return onAgain;       }       if (pointList.isNotEmpty &amp;&amp; pointAgainList.isNotEmpty) {         if (!const ListEquality().equals(pointList, pointAgainList)) {           // shownText = '两次图案不一样，请重新绘制';           return onNotEquals;         } else {           // shownText = '正在设置...';           return onSuccess;         }       }       // return Text(shownText ?? '请绘制解锁图案');       return onDefault;     });   } }  
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
