### ISSUE TITLE
selectedItem 位置不对

### ISSUE THREAD

**Issue by ltxhhz** [LuodiJackShen/GesturePasswordWidget#6]
我在安卓和web平台的测试都是如图的效果
![GIF](https://user-images.githubusercontent.com/51697596/205090789-a4f3c340-4438-4644-b696-3bb3b8931f55.gif)

如果能将这里的 `Stack` 的参数
https://github.com/LuodiJackShen/GesturePasswordWidget/blob/f321b2ba96feb557c2981d3565a0940ac478e334/lib/widget/gesture_password_widget.dart#L405-L416
新增一行 `alignment: AlignmentDirectional.center,`
则可以修复

**Comment by LuodiJackShen** [comment]
把你代码贴出来，我这没复现呢

**Comment by LuodiJackShen** [comment]
demo工程也没复现

**Comment by ltxhhz** [comment]
我这里给一个 `arrowItem`就会出现这个问题
```dart
import 'package:flutter/material.dart';
import 'package:gesture_password_widget/gesture_password_widget.dart';

class TestPage extends StatelessWidget {
  const TestPage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('test')),
      body: Container(
        child: GesturePasswordWidget(
          arrowItem: const Icon(Icons.arrow_right),
        ),
      ),
    );
  }
}
```

**Comment by LuodiJackShen** [comment]
已经提交pub.dev
